In [1]:
%reload_ext autoreload
%autoreload 2

import os
import sys
sys.path.insert(1, os.path.join(sys.path[0], '..'))

In [2]:
import numpy as np
import pandas as pd
import scipy.linalg
import time

from src.graph import visualize
from src.recommender import train_mf, reviews_dataset, evaluate_recommendations
from src.recommender.mf_recommender import train_mf, preprocess, get_reviews_by_user, compute_X
from src.tags import PytorchWordEmbedding

In [3]:
reviews_train, reviews_validation, reviews_test, images = reviews_dataset()

In [4]:
train_data, I, tags, n, m, k = preprocess(reviews_train, images)

image_indices, ratings, start_index, end_index = get_reviews_by_user(train_data)

In [6]:
d = 20
alpha = .1

X = np.random.normal(size=(n, d))
Y = np.random.normal(size=(k, d))

for als_epoch in range(1):
    start = time.time()
    compute_X(
            X=X,
            Y=Y,
            I=I,
            image_indices=image_indices,
            ratings=ratings,
            start_index=start_index,
            end_index=end_index,
            n=n,
            k=k,
            d=d,
            alpha=alpha,
        )
    end = time.time()
    print(f"{end - start:.2f}")
    
    raise RuntimeError

    compute_Y()

112.56


RuntimeError: 

In [ ]:
recommender = train_mf(
    reviews_train,
    images,
    d = 20,
    alpha = .01,
    beta = .01,
    als_epochs = 1,
    sgd_learning_rate = .1,
    sgd_epochs = 10,
    sgd_batch_size = 10,
)

Precomputing reviews_by_user
Elapsed: 47.28s
[    0 35968 10499 32248 26487]
<class 'numpy.ndarray'>
(5592224,)
[5. 5. 5. 5. 5.]
<class 'numpy.ndarray'>
(5592224,)
[  0  37 141 177 186]
<class 'numpy.ndarray'>
(1746429,)
[ 37 141 177 186 189]
<class 'numpy.ndarray'>
(1746429,)
Computing X


OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.


In [5]:
reviews_validation_by_user = reviews_validation.groupby("user_index").apply(lambda group: (group["image_index"].to_numpy(), group["rating"].to_numpy()))

KeyError: 'user_index'

In [ ]:
validation_loss = 1/n * sum(1 / len(image_ids) * sum((ratings - image_tags[image_ids] @ (Y @ X[u])) ** 2) for u, (image_ids, ratings) in reviews_validation_by_user.items() if len(image_ids) > 0)
validation_loss

In [ ]:
recommender = train_knn(reviews_train, word_embedding)

In [ ]:
visualize(recommender.graph, {vertex: vertex.id for vertex in recommender.graph.vertices})

In [ ]:
evaluate_recommendations(recommender, reviews_validation)