In [1]:
%reload_ext autoreload
%autoreload 2

import os
import sys
sys.path.insert(1, os.path.join(sys.path[0], '..'))

In [40]:
import numpy as np
import pandas as pd
import scipy.linalg
import time

from src.graph import visualize
from src.recommender import train_mf, reviews_dataset, evaluate_recommendations
from src.recommender.mf_recommender import train_mf, preprocess, get_reviews_by_user, compute_X
from src.tags import PytorchWordEmbedding

In [38]:
reviews_train, reviews_validation, reviews_test, images = reviews_dataset()

In [39]:
train_data, I, tags, n, m, k = preprocess(train_data, images)

image_indices, ratings, start_index, end_index = get_reviews_by_user(train_data)

In [49]:
d = 20
alpha = .1

X = np.random.normal(size=(n, d))
Y = np.random.normal(size=(k, d))

for als_epoch in range(1):
    compute_X(
            X=X,
            Y=Y,
            I=I,
            image_indices=image_indices,
            ratings=ratings,
            start_index=start_index,
            end_index=end_index,
            n=n,
            k=k,
            d=d,
            alpha=alpha,
        )
    
    raise RuntimeError

    compute_Y()

10000 users processed, 7.58s elapsed, 7.579322814941406s average
20000 users processed, 11.51s elapsed, 5.754663944244385s average
30000 users processed, 14.58s elapsed, 4.861420313517253s average
40000 users processed, 17.14s elapsed, 4.285180985927582s average
50000 users processed, 20.39s elapsed, 4.077080774307251s average
60000 users processed, 24.48s elapsed, 4.080824494361877s average
70000 users processed, 26.78s elapsed, 3.8262914248875206s average


KeyboardInterrupt: 

In [ ]:
recommender = train_mf(
    reviews_train,
    images,
    d = 20,
    alpha = .01,
    beta = .01,
    als_epochs = 1,
    sgd_learning_rate = .1,
    sgd_epochs = 10,
    sgd_batch_size = 10,
)

Precomputing reviews_by_user
Elapsed: 47.28s
[    0 35968 10499 32248 26487]
<class 'numpy.ndarray'>
(5592224,)
[5. 5. 5. 5. 5.]
<class 'numpy.ndarray'>
(5592224,)
[  0  37 141 177 186]
<class 'numpy.ndarray'>
(1746429,)
[ 37 141 177 186 189]
<class 'numpy.ndarray'>
(1746429,)
Computing X


OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.


In [5]:
reviews_validation_by_user = reviews_validation.groupby("user_index").apply(lambda group: (group["image_index"].to_numpy(), group["rating"].to_numpy()))

KeyError: 'user_index'

In [ ]:
validation_loss = 1/n * sum(1 / len(image_ids) * sum((ratings - image_tags[image_ids] @ (Y @ X[u])) ** 2) for u, (image_ids, ratings) in reviews_validation_by_user.items() if len(image_ids) > 0)
validation_loss

In [ ]:
recommender = train_knn(reviews_train, word_embedding)

In [ ]:
visualize(recommender.graph, {vertex: vertex.id for vertex in recommender.graph.vertices})

In [ ]:
evaluate_recommendations(recommender, reviews_validation)